ALTER TYPE "OrderStatus" RENAME VALUE 'PENDING' TO 'SENT_TO_KITCHEN';
ALTER TYPE "OrderStatus" RENAME VALUE 'PROCESSING' TO 'READY';
ALTER TYPE "OrderStatus" RENAME VALUE 'COMPLETED' TO 'DELIVERED_PAID';
ALTER TYPE "OrderStatus" ADD VALUE 'PACKED' AFTER 'READY';
