ALTER TABLE "Product"
ALTER COLUMN "stockQuantity" TYPE DOUBLE PRECISION
USING "stockQuantity"::DOUBLE PRECISION;

ALTER TABLE "InventorySessionItem"
ALTER COLUMN "stockQuantity" TYPE DOUBLE PRECISION
USING "stockQuantity"::DOUBLE PRECISION,
ALTER COLUMN "actualQuantity" TYPE DOUBLE PRECISION
USING "actualQuantity"::DOUBLE PRECISION;

ALTER TABLE "WriteoffActItem"
ALTER COLUMN "quantity" TYPE DOUBLE PRECISION
USING "quantity"::DOUBLE PRECISION,
ALTER COLUMN "stockQuantityBefore" TYPE DOUBLE PRECISION
USING "stockQuantityBefore"::DOUBLE PRECISION,
ALTER COLUMN "stockQuantityAfter" TYPE DOUBLE PRECISION
USING "stockQuantityAfter"::DOUBLE PRECISION;
